/**
 * 다이어리 작성 화면
 * 제목, 내용, 기분 입력
 */

import React, { useState, useEffect } from 'react';
import {
  View,
  Text,
  StyleSheet,
  TouchableOpacity,
  TextInput,
  ScrollView,
  Alert,
  ActivityIndicator,
} from 'react-native';
import { useRouter, useLocalSearchParams } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { createDiary, getSuggestedTodos, acceptSuggestedTodos, getDiaryByCall } from '../api/diary';
import { getCallLog } from '../api/call';

// 기분 옵션
const MOOD_OPTIONS = [
  { value: 'happy', label: '행복해요', emoji: '😊' },
  { value: 'excited', label: '신나요', emoji: '🤗' },
  { value: 'calm', label: '평온해요', emoji: '😌' },
  { value: 'sad', label: '슬퍼요', emoji: '😢' },
  { value: 'angry', label: '화나요', emoji: '😠' },
  { value: 'tired', label: '피곤해요', emoji: '😴' },
];

export const DiaryWriteScreen = () => {
  const router = useRouter();
  const insets = useSafeAreaInsets();
  
  // URL 파라미터에서 통화 정보 가져오기
  const searchParams = useLocalSearchParams();
  const fromCall = searchParams.fromCall === 'true';
  const callSid = searchParams.callSid as string | undefined;

  const [date, setDate] = useState(new Date().toISOString().split('T')[0]); // YYYY-MM-DD
  const [title, setTitle] = useState('');
  const [content, setContent] = useState('');
  const [selectedMood, setSelectedMood] = useState<string>('');
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [isLoadingSummary, setIsLoadingSummary] = useState(false);
  
  // TODO 관련 상태
  const [suggestedTodos, setSuggestedTodos] = useState<any[]>([]);
  const [selectedTodos, setSelectedTodos] = useState<number[]>([]);
  const [isLoadingTodos, setIsLoadingTodos] = useState(false);
  const [showTodoSection, setShowTodoSection] = useState(false);
  const [generatedDiaryId, setGeneratedDiaryId] = useState<string | null>(null);

  /**
   * 날짜 포맷팅
   */
  const formatDateDisplay = (dateString: string): string => {
    const d = new Date(dateString);
    const year = d.getFullYear();
    const month = d.getMonth() + 1;
    const day = d.getDate();
    const days = ['일', '월', '화', '수', '목', '금', '토'];
    const dayOfWeek = days[d.getDay()];
    return `${year}년 ${month}월 ${day}일 (${dayOfWeek})`;
  };

  /**
   * 자동 생성된 일기 불러오기
   */
  useEffect(() => {
    const loadAutoGeneratedDiary = async () => {
      // 통화에서 온 경우이고 callSid가 있을 때만 실행
      if (fromCall && callSid) {
        try {
          setIsLoadingSummary(true);
          console.log('📝 자동 생성된 일기 불러오기 시작:', callSid);
          
          // 일기 생성 완료까지 대기 (최대 15초, 3초마다 재시도)
          let retryCount = 0;
          const maxRetries = 5;
          
          const checkDiary = async (): Promise<boolean> => {
            try {
              const diary = await getDiaryByCall(callSid);
              if (diary && diary.is_auto_generated) {
                // 자동 생성된 일기를 content에 입력
                setContent(diary.content);
                setTitle('AI와의 대화 일기');
                setGeneratedDiaryId(diary.diary_id);
                
                console.log('✅ 자동 생성된 일기 불러오기 완료');
                
                Alert.alert(
                  '✅ 일기 자동 완성',
                  'AI가 통화 내용으로 일기를 작성했습니다!\n수정하거나 그대로 저장할 수 있습니다.',
                  [{ text: '확인' }]
                );
                
                return true;
              }
              return false;
            } catch (error) {
              return false;
            }
          };
          
          // 재시도 로직
          const waitForDiary = async () => {
            while (retryCount < maxRetries) {
              console.log(`📋 일기 확인 중... (${retryCount + 1}/${maxRetries})`);
              
              const found = await checkDiary();
              if (found) {
                return true;
              }
              
              retryCount++;
              if (retryCount < maxRetries) {
                await new Promise(resolve => setTimeout(resolve, 3000));
              }
            }
            return false;
          };
          
          const success = await waitForDiary();
          
          if (!success) {
            console.log('⚠️ 자동 생성된 일기를 찾을 수 없음');
            Alert.alert(
              '알림',
              '일기가 아직 생성되지 않았습니다.\n직접 작성해주세요.'
            );
          }
          
        } catch (error) {
          console.error('❌ 일기 불러오기 실패:', error);
          Alert.alert(
            '알림',
            '일기를 불러오지 못했습니다.\n직접 작성해주세요.'
          );
        } finally {
          setIsLoadingSummary(false);
        }
      }
    };

    loadAutoGeneratedDiary();
    
    // TODO 로딩도 함께 실행
    loadSuggestedTodos();
  }, [fromCall, callSid]);

  /**
   * 감지된 TODO 불러오기
   */
  const loadSuggestedTodos = async () => {
    if (!fromCall || !callSid) return;
    
    try {
      setIsLoadingTodos(true);
      console.log('📋 감지된 TODO 불러오기 시작');
      
      // TODO 조회 (최대 15초까지 재시도)
      let retryCount = 0;
      const maxRetries = 5;
      
      const checkTodos = async (): Promise<boolean> => {
        try {
          const diary = await getDiaryByCall(callSid);
          if (diary && diary.is_auto_generated) {
            setGeneratedDiaryId(diary.diary_id);
            
            const todos = await getSuggestedTodos(diary.diary_id);
            if (todos.suggested_todos && todos.suggested_todos.length > 0) {
              setSuggestedTodos(todos.suggested_todos);
              setShowTodoSection(true);
              console.log(`📌 ${todos.suggested_todos.length}개의 TODO 감지됨`);
              return true;
            }
          }
          return false;
        } catch (error) {
          return false;
        }
      };
      
      // 재시도 로직
      const waitForTodos = async () => {
        while (retryCount < maxRetries) {
          console.log(`📋 TODO 확인 중... (${retryCount + 1}/${maxRetries})`);
          
          const found = await checkTodos();
          if (found) {
            setIsLoadingTodos(false);
            return;
          }
          
          retryCount++;
          if (retryCount < maxRetries) {
            await new Promise(resolve => setTimeout(resolve, 3000));
          }
        }
        setIsLoadingTodos(false);
        console.log('⚠️ TODO를 찾을 수 없음');
      };
      
      waitForTodos();
      
    } catch (error) {
      console.error('❌ TODO 불러오기 실패:', error);
      setIsLoadingTodos(false);
    }
  };

  /**
   * TODO 선택/해제
   */
  const toggleTodoSelection = (index: number) => {
    setSelectedTodos(prev => 
      prev.includes(index) 
        ? prev.filter(i => i !== index)
        : [...prev, index]
    );
  };

  /**
   * 선택된 TODO 등록
   */
  const handleAcceptTodos = async () => {
    if (selectedTodos.length === 0) {
      Alert.alert('알림', '등록할 할 일을 선택해주세요.');
      return;
    }

    try {
      setIsSubmitting(true);
      console.log('📝 선택된 TODO 등록 시작:', selectedTodos);
      
      if (!generatedDiaryId) {
        Alert.alert('오류', '일기 정보를 찾을 수 없습니다.');
        return;
      }
      
      const result = await acceptSuggestedTodos(generatedDiaryId, selectedTodos);
      console.log('✅ TODO 등록 완료:', result);
      
      Alert.alert(
        '완료',
        `${result.created_todos_count}개의 할 일이 등록되었습니다! 📋`,
        [{ text: '확인' }]
      );
      
      // TODO 섹션 숨기기
      setShowTodoSection(false);
      setSelectedTodos([]);
      
    } catch (error: any) {
      console.error('❌ TODO 등록 실패:', error);
      Alert.alert(
        '오류',
        error.response?.data?.detail || '할 일 등록에 실패했습니다.'
      );
    } finally {
      setIsSubmitting(false);
    }
  };

  /**
   * 일기 저장
   */
  const handleSubmit = async () => {
    // 유효성 검사
    if (!title.trim()) {
      Alert.alert('알림', '제목을 입력해주세요.');
      return;
    }

    if (!selectedMood) {
      Alert.alert('알림', '오늘의 기분을 선택해주세요.');
      return;
    }

    if (!content.trim()) {
      Alert.alert('알림', '일기 내용을 입력해주세요.');
      return;
    }

    try {
      setIsSubmitting(true);

      await createDiary({
        date,
        title: title.trim(),
        content: content.trim(),
        mood: selectedMood,
        status: 'published',
      });

      // 성공 메시지 표시
      Alert.alert(
        '완료',
        '일기가 저장되었습니다! 📝',
        [
          {
            text: '확인',
            onPress: () => {
              // 통화에서 온 경우 메인 페이지로, 아니면 다이어리 목록으로 이동
              if (fromCall) {
                // 통화 → 다이어리 작성 → 메인 (뒤로가기 스택 초기화)
                router.replace('/home');
              } else {
                // 일반 다이어리 작성 → 다이어리 목록
                router.replace('/diaries');
              }
            },
          },
        ]
      );

    } catch (error: any) {
      console.error('일기 저장 실패:', error);
      Alert.alert(
        '오류',
        error.response?.data?.detail || '일기 저장에 실패했습니다.'
      );
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <View style={[styles.container, { paddingTop: insets.top }]}>
      {/* 헤더 */}
      <View style={styles.header}>
        <TouchableOpacity
          onPress={() => {
            // 통화에서 온 경우 메인으로, 아니면 뒤로가기
            if (fromCall) {
              router.replace('/home');
            } else {
              router.back();
            }
          }}
          style={styles.backButton}
          disabled={isSubmitting}
        >
          <Text style={styles.backButtonText}>←</Text>
        </TouchableOpacity>
        <Text style={styles.headerTitle}>일기 작성</Text>
        <View style={styles.placeholder} />
      </View>

      <ScrollView
        style={styles.scrollView}
        contentContainerStyle={styles.content}
        showsVerticalScrollIndicator={false}
      >
        {/* 일기 생성 로딩 인디케이터 */}
        {isLoadingSummary && (
          <View style={styles.loadingContainer}>
            <ActivityIndicator size="small" color="#4A90E2" />
            <Text style={styles.loadingText}>AI가 일기를 생성하는 중...</Text>
          </View>
        )}

        {/* TODO 로딩 인디케이터 */}
        {isLoadingTodos && (
          <View style={styles.loadingContainer}>
            <ActivityIndicator size="small" color="#34B79F" />
            <Text style={styles.loadingText}>감지된 할 일을 확인하는 중...</Text>
          </View>
        )}

        {/* 감지된 TODO 섹션 */}
        {showTodoSection && suggestedTodos.length > 0 && (
          <View style={styles.todoSection}>
            <Text style={styles.todoSectionTitle}>🤖 AI가 감지한 할 일</Text>
            <Text style={styles.todoSectionSubtitle}>
              통화 내용에서 감지된 할 일입니다. 등록하고 싶은 항목을 선택해주세요.
            </Text>
            
            {suggestedTodos.map((todo, index) => (
              <TouchableOpacity
                key={index}
                style={[
                  styles.todoItem,
                  selectedTodos.includes(index) && styles.todoItemSelected
                ]}
                onPress={() => toggleTodoSelection(index)}
                disabled={isSubmitting}
              >
                <View style={styles.todoItemContent}>
                  <Text style={styles.todoItemTitle}>{todo.title}</Text>
                  {todo.description && (
                    <Text style={styles.todoItemDescription}>{todo.description}</Text>
                  )}
                  <View style={styles.todoItemMeta}>
                    <Text style={styles.todoItemDate}>
                      📅 {todo.due_date ? new Date(todo.due_date).toLocaleDateString('ko-KR') : '날짜 미정'}
                    </Text>
                    <Text style={[
                      styles.todoItemPriority,
                      { color: todo.priority === 'high' ? '#FF6B6B' : todo.priority === 'medium' ? '#FFA726' : '#66BB6A' }
                    ]}>
                      {todo.priority === 'high' ? '🔴 높음' : todo.priority === 'medium' ? '🟡 보통' : '🟢 낮음'}
                    </Text>
                  </View>
                </View>
                <View style={[
                  styles.todoCheckbox,
                  selectedTodos.includes(index) && styles.todoCheckboxSelected
                ]}>
                  {selectedTodos.includes(index) && (
                    <Text style={styles.todoCheckmark}>✓</Text>
                  )}
                </View>
              </TouchableOpacity>
            ))}
            
            <View style={styles.todoActions}>
              <TouchableOpacity
                style={[
                  styles.todoActionButton,
                  selectedTodos.length === 0 && styles.todoActionButtonDisabled
                ]}
                onPress={handleAcceptTodos}
                disabled={selectedTodos.length === 0 || isSubmitting}
              >
                <Text style={[
                  styles.todoActionButtonText,
                  selectedTodos.length === 0 && styles.todoActionButtonTextDisabled
                ]}>
                  📋 선택한 할 일 등록 ({selectedTodos.length}개)
                </Text>
              </TouchableOpacity>
              
              <TouchableOpacity
                style={styles.todoSkipButton}
                onPress={() => setShowTodoSection(false)}
                disabled={isSubmitting}
              >
                <Text style={styles.todoSkipButtonText}>건너뛰기</Text>
              </TouchableOpacity>
            </View>
          </View>
        )}

        {/* 날짜 (숨김 - 자동으로 오늘 날짜) */}
        <View style={styles.section}>
          <Text style={styles.dateText}>{formatDateDisplay(date)}</Text>
        </View>

        {/* 제목 */}
        <View style={styles.section}>
          <Text style={styles.sectionLabel}>제목</Text>
          <TextInput
            style={styles.titleInput}
            placeholder="제목을 입력하세요"
            placeholderTextColor="#CCCCCC"
            value={title}
            onChangeText={setTitle}
            maxLength={100}
            editable={!isSubmitting}
          />
        </View>

        {/* 기분 */}
        <View style={styles.section}>
          <Text style={styles.sectionLabel}>오늘의 기분</Text>
          <View style={styles.moodGrid}>
            {MOOD_OPTIONS.map((mood) => (
              <TouchableOpacity
                key={mood.value}
                style={[
                  styles.moodButton,
                  selectedMood === mood.value && styles.moodButtonSelected,
                ]}
                onPress={() => setSelectedMood(mood.value)}
                disabled={isSubmitting}
              >
                <Text style={styles.moodEmoji}>{mood.emoji}</Text>
                <Text
                  style={[
                    styles.moodLabel,
                    selectedMood === mood.value && styles.moodLabelSelected,
                  ]}
                >
                  {mood.label}
                </Text>
              </TouchableOpacity>
            ))}
          </View>
        </View>

        {/* 내용 */}
        <View style={styles.section}>
          <Text style={styles.sectionLabel}>일기 내용</Text>
          <TextInput
            style={styles.contentInput}
            placeholder="오늘 하루는 어떠셨나요?&#10;일어난 일이나 느낀 점을 자유롭게 작성해보세요."
            placeholderTextColor="#CCCCCC"
            value={content}
            onChangeText={setContent}
            multiline
            numberOfLines={15}
            textAlignVertical="top"
            editable={!isSubmitting}
          />
          <Text style={styles.charCount}>{content.length}자</Text>
        </View>

        {/* 저장 버튼 */}
        <TouchableOpacity
          onPress={handleSubmit}
          style={[styles.submitButton, isSubmitting && styles.submitButtonDisabled]}
          disabled={isSubmitting}
        >
          {isSubmitting ? (
            <ActivityIndicator size="small" color="#FFFFFF" />
          ) : (
            <Text style={styles.submitButtonText}>✏️ 작성하기</Text>
          )}
        </TouchableOpacity>
      </ScrollView>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#E8E8E8',
  },
  backButton: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  backButtonText: {
    fontSize: 28,
    color: '#333333',
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#333333',
  },
  placeholder: {
    width: 40,
  },
  scrollView: {
    flex: 1,
  },
  content: {
    padding: 20,
    paddingBottom: 100,
  },
  section: {
    marginBottom: 24,
  },
  sectionLabel: {
    fontSize: 15,
    fontWeight: '600',
    color: '#333333',
    marginBottom: 12,
  },
  dateText: {
    fontSize: 16,
    fontWeight: '500',
    color: '#34B79F',
    textAlign: 'center',
  },
  titleInput: {
    fontSize: 18,
    color: '#333333',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: '#E8E8E8',
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
  },
  moodGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  moodButton: {
    width: '30%',
    paddingVertical: 16,
    backgroundColor: '#F8F8F8',
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: 'transparent',
  },
  moodButtonSelected: {
    backgroundColor: '#E8F5F2',
    borderColor: '#34B79F',
  },
  moodEmoji: {
    fontSize: 26,
    marginBottom: 4,
  },
  moodLabel: {
    fontSize: 12,
    fontWeight: '500',
    color: '#666666',
  },
  moodLabelSelected: {
    color: '#34B79F',
    fontWeight: '700',
  },
  contentInput: {
    fontSize: 16,
    lineHeight: 24,
    color: '#333333',
    padding: 16,
    borderWidth: 1,
    borderColor: '#E8E8E8',
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    minHeight: 240,
  },
  charCount: {
    fontSize: 13,
    color: '#999999',
    textAlign: 'right',
    marginTop: 8,
  },
  submitButton: {
    width: '100%',
    height: 56,
    backgroundColor: '#34B79F',
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 24,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
  },
  submitButtonDisabled: {
    backgroundColor: '#CCCCCC',
  },
  submitButtonText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  loadingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
    backgroundColor: '#F0F8FF',
    borderRadius: 12,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#D0E8FF',
  },
  loadingText: {
    marginLeft: 8,
    fontSize: 14,
    color: '#4A90E2',
    fontWeight: '500',
  },
  // TODO 섹션 스타일
  todoSection: {
    backgroundColor: '#F8F9FA',
    borderRadius: 16,
    padding: 20,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: '#E8F5F2',
  },
  todoSectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#34B79F',
    marginBottom: 8,
  },
  todoSectionSubtitle: {
    fontSize: 14,
    color: '#666666',
    marginBottom: 16,
    lineHeight: 20,
  },
  todoItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    borderWidth: 2,
    borderColor: '#E8E8E8',
  },
  todoItemSelected: {
    borderColor: '#34B79F',
    backgroundColor: '#F0F8F5',
  },
  todoItemContent: {
    flex: 1,
  },
  todoItemTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333333',
    marginBottom: 4,
  },
  todoItemDescription: {
    fontSize: 14,
    color: '#666666',
    marginBottom: 8,
  },
  todoItemMeta: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  todoItemDate: {
    fontSize: 12,
    color: '#999999',
  },
  todoItemPriority: {
    fontSize: 12,
    fontWeight: '600',
  },
  todoCheckbox: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#CCCCCC',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 12,
  },
  todoCheckboxSelected: {
    backgroundColor: '#34B79F',
    borderColor: '#34B79F',
  },
  todoCheckmark: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  todoActions: {
    marginTop: 16,
  },
  todoActionButton: {
    backgroundColor: '#34B79F',
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 20,
    alignItems: 'center',
    marginBottom: 12,
  },
  todoActionButtonDisabled: {
    backgroundColor: '#CCCCCC',
  },
  todoActionButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  todoActionButtonTextDisabled: {
    color: '#999999',
  },
  todoSkipButton: {
    alignItems: 'center',
    paddingVertical: 8,
  },
  todoSkipButtonText: {
    color: '#999999',
    fontSize: 14,
  },
});

export default DiaryWriteScreen;

