"""add_kakao_oauth_fields

Revision ID: ff12a5125c44
Revises: 7c30e54c1546
Create Date: 2025-10-14 06:02:33.693461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff12a5125c44'
down_revision: Union[str, None] = '7c30e54c1546'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('kakao_id', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('kakao_access_token', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('kakao_refresh_token', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('birth_date', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('gender', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_users_kakao_id'), 'users', ['kakao_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_kakao_id'), table_name='users')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'birth_date')
    op.drop_column('users', 'kakao_refresh_token')
    op.drop_column('users', 'kakao_access_token')
    op.drop_column('users', 'kakao_id')
    # ### end Alembic commands ###

