"""add_title_and_mood_to_diary

Revision ID: f29426160b6d
Revises: 302c7ff1293d
Create Date: 2025-10-16 06:58:03.288970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f29426160b6d'
down_revision: Union[str, None] = '302c7ff1293d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diaries', sa.Column('title', sa.String(length=200), nullable=True))
    op.add_column('diaries', sa.Column('mood', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diaries', 'mood')
    op.drop_column('diaries', 'title')
    # ### end Alembic commands ###

